#!/usr/bin/env python3

import argparse
import sys
from sitemapbuilder import LinkVisitor
from sitemapbuilder import SameHostnameFilter
from sitemapbuilder import convert_to_dot

parser = argparse.ArgumentParser()
parser.add_argument('-d', '--decay', type=int, help='maximum depth',
                    default=2)
parser.add_argument('-u', '--url', type=str, help='seed URL to fetch',
                    required=True)
parser.add_argument('-o', '--out-file', type=str, help='output file name',
                    required=True)

args = parser.parse_args()

link_visitor = LinkVisitor(args.url, args.decay, SameHostnameFilter(args.url))
link_visitor.start()
dot_str = convert_to_dot(link_visitor.sitemap)
with open(args.out_file, 'wb') as out_file:
    out_file.write(dot_str.encode('utf-8'))
print("Generated the sitemap file [%s]" % args.out_file)
